# Generated by Django 3.1.5 on 2021-09-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipcode',
            old_name='product_quantity',
            new_name='zipcode',
        ),
    ]
