# Generated by Django 3.1.5 on 2021-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210930_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zipcode',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
